### ISSUE TITLE
SocketRocket in combination with HTTP proxy

### ISSUE THREAD

**Issue by slehrack** [facebook/SocketRocket#344] opened 2016-03-29 14:57 UTC
Hi,

we try to set up a WebSocket connection from a MacOS client that uses a HTTP proxy. Unfortunately,
the connection fails to open. 
   
Can we give the proxy settings for establishing the WebSocket connection somehow explicitly?
Is it possible to use SocketRocket in combination with a proxy?

A curl call and a java client are able to connect, when we extend them with the necessary
proxy parameters. So, in principle, the WebSocket service is reachable without adjusting the proxy server.

A simple NSURLConnection-based request also works.

Thanks for any help and hints.

**Comment by rahulsh1** [comment] 2016-04-03 05:19
There is already a feature request open [here](https://github.com/square/SocketRocket/issues/114).

**Comment by nlutsenko** [comment] 2016-05-12 03:56
Closing as duplicate of #114

**Closed by nlutsenko** 2016-05-12 03:56 UTC
